SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";



CREATE DATABASE IF NOT EXISTS `trvl` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `trvl`;
